# -*- coding: utf-8 -*-
"""Day02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I56CkaIFai4TEkBQg4bnMfOU5LTeIY6R
"""

weather = "rainy"

if weather == "sunny":
    print("Wear shorts!")
    print("check statement")
    print("hello")
elif weather == "rainy":
    print("Wear a raincoat!")
elif weather == "cold":
    print("waer a sweater")
else:
    print("Wear a normal clothes!")
print("outside if statement")

weather = "wind"
temperature = "cold"

if weather == "sunny":
    if temperature == "hot":
        print("Wear shorts!")
    else:
        print("Wear a light jacket!")
else:
    if weather == "rainy":
        print("Take an umbrella!")
    else:
        print("Wear something normal!")



if weather=="sunny":
  print("shorts")
else:
  print("normal")

2==4

2==2

a=12
b=14

if a==b:
  print("yes")
else
  print("no")

a!=b

a>b

a<b

a<=b

a=12
b=12
a<=b

a>=b

from re import X
if <condition> :
  if the above condition is true these below will Execute
  a
  v
  c

else:
  these will execute
  abs
  b
  X

age = 12

if age >= 13:
    print("You can watch a PG-13 movie!")
else:
    print("You are too young to watch a PG-13 movie.")

print("hi")
print("hi")
print("hi")
print("hi")
print("hi")

for i in range(5):
  print("hi")

for loop and while loop

# List of fruits
fruits = ["apple", "banana", "cherry"]

# Loop through each fruit and print it
for x in fruits:
    print(x)
    print("hi")

print("end loop")

number = 1

while number <= 5:#6<=5 as this is false
    print(number)
    print("hello")
    number = 2 + 1 # number = 2 + 1 the new value of number will become 3
    #new value number is 3
    #last itiration number = 5+1 ie 6
print("end loop")

number = 1
number = number + 1
print(number)

var = "value"
var = var + "value"
#interpretation of python
var = "value" + "value"

var

for i in range(1,6):
  print(i)

#range(a,b)=[a, a+1,a+2,....,b-1] condition to remember for range a<b

for i in range(1, 6):
    print(i)#1st statment
    break#2nd statment
    print(i)#3rd statment
#outside side the loop

print("end loop")

# continue example
for i in range(1, 6):
    if i == 3:
        print("now i is 3")
        continue  # Skips printing 3 and goes to the next number
    print(i)
    print("hello")

for i in range(1,6):
  print(i)# 1st
  print("hi")#2nd
  continue#3rd
  print("hello")#4th

for i in range(1, 6):
    if i == 3:
        pass  # Does nothing special when i is 3
    print(i)

for i in range(1,6):
  pass

if a<b:
  pass

#conditional statement that if, elif, else
# conditional operators ==,!=, <, >, <=, >=
#loops for, while
#loop control statements those are break, continue, pass

